name: unit_test
on: [push, workflow_dispatch]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2.10.0
    - run: flutter pub get
    - run: flutter test --platform=chrome